#!/bin/bash

/bin/chown pe-razor:pe-razor /opt/puppetlabs/var/razor 2> /dev/null ||:
/bin/chown pe-razor:pe-razor /opt/puppetlabs/server/apps/razor-server/share/razor-server/config.ru 2>/dev/null ||:
